# docker-compose.yml
services:
    app:
        image: aloxbro/hello-app
    server:
        build: ./server
        ports:
            - 5050:5000
        command: npm run dev
        volumes: 
            - ./server/src/:/app/src/
    mongodb:
        image: mongo
        volumes:
            - ./data:/data/db
    client:
        build: ./client/dockerquest-app
        command: npm start
        ports:
            - 8080:3000
        environment:
            - CHOKIDAR_USEPOLLING=true
    